const assert=require('node:assert/strict');const {World}=require('./engine.js');let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name)}function tick(w,s,input={}){for(let i=0;i<Math.ceil(s*120);i++)w.update(1/120,input)}function fresh(){let w=new World();w.drain();return w}function has(w,id){return w.drain().some(e=>e.id===id)}
test('intro / reset',()=>{let w=new World();assert(has(w,'intro'));assert.equal(w.enemies.length,10);w.reset();assert.equal(w.falls,0)});
test('movement / facing / double jump / landing',()=>{let w=fresh();tick(w,.5,{right:true});assert(w.player.x>300);tick(w,.4,{left:true});assert.equal(w.player.face,-1);w.jump();assert.equal(w.player.jumps,1);w.jump();assert.equal(w.player.jumps,2);let vy=w.player.vy;w.jump();assert.equal(w.player.vy,vy);tick(w,2);assert(w.player.ground);assert.equal(w.player.jumps,0)});
test('dash / roll / invulnerability / cooldown',()=>{let w=fresh(),p=w.player;w.dash();assert(p.inv>0);assert.equal(w.damage(20,1),false);tick(w,.1);assert(p.x>320);tick(w,.7);w.dash(true);assert(p.roll>0);assert.equal(w.damage(20,1),false)});
test('three light combos / hitstop / charge restoration',()=>{let w=fresh(),p=w.player,e=w.enemies[0];w.enemies=[e];e.x=p.x+65;e.hp=500;p.energy=20;for(let n=1;n<=3;n++){e.x=p.x+65;w.attack('light');assert.equal(p.combo,n);assert(w.hitstop>0);tick(w,.33)}assert.equal(w.hits,3);assert(p.energy>40);assert.equal(w.chain,3)});
test('heavy launcher / charged smash / air slash',()=>{let w=fresh(),e=w.enemies[0];e.x=280;w.attack('heavy',.1);assert(e.vy<0);tick(w,.6);e.x=w.player.x+60;e.y=w.player.y;e.hp=100;w.attack('heavy',.8);assert.equal(e.hp,32);tick(w,.6);w.player.attack=0;w.player.y=e.y-10;w.attack('light');assert(e.hp<32)});
test('electric resource gate / area attack / boss victory',()=>{let w=fresh(),p=w.player,b=w.enemies.find(e=>e.type==='boss');p.energy=20;assert(!w.attack('electric'));p.energy=100;p.x=b.x-100;b.hp=90;assert(w.attack('electric'));assert(w.won);assert(b.dead);assert(has(w,'bossdead'));p.x=3100;w.interact();assert(w.coreSeen);assert(w.drain().some(e=>e.type==='ending'))});
test('left / real cliff falling three times / achievement / room / return',()=>{let w=fresh();w.player.x=80;tick(w,.03);assert(has(w,'left'));for(let i=0;i<3;i++){w.player.x=-100;w.player.y=500;w.player.vy=0;tick(w,1);assert.equal(w.falls,i+1)}assert(has(w,'rebel'));w.interact();assert(w.room);assert(has(w,'room'));w.interact();assert(w.roomSeen);assert(has(w,'monument'));w.player.x=-430;w.interact();assert(!w.room)});
test('idle story / one-time story dedupe',()=>{let w=fresh();w.enemies=[];tick(w,12.2);assert(has(w,'idle'));tick(w,2);assert(!has(w,'idle'));w.say('intro','duplicate');assert(!has(w,'intro'))});
test('spider warning / detonation / damage',()=>{let w=fresh(),e=w.enemies[0];w.enemies=[e];e.x=250;tick(w,.8);assert(e.dead);assert(w.player.hp<100);assert(w.drain().some(e=>e.type==='explosion'))});
test('drone telegraph / laser',()=>{let w=fresh(),e=w.enemies.find(e=>e.type==='drone');w.enemies=[e];e.x=300;e.cool=0;tick(w,1);assert(w.drain().some(e=>e.type==='laser'))});
test('boss telegraph / slam / phase two / narrative',()=>{let w=fresh(),e=w.enemies.find(e=>e.type==='boss');w.enemies=[e];w.player.x=e.x-90;e.cool=0;e.hp=200;tick(w,1);let events=w.drain();assert(events.some(e=>e.id==='boss'));assert(events.some(e=>e.type==='slam'&&e.radius===245));assert(w.player.hp<100)});
test('death checkpoint / regeneration / bounds / combo expiry',()=>{let w=fresh();w.enemies=[];w.player.hp=1;w.damage(30,1);assert.equal(w.player.hp,100);assert(has(w,'death'));w.player.hp=80;tick(w,10);assert(w.player.hp>80);w.player.x=5000;tick(w,.1);assert(w.player.x<=3290);w.chain=4;w.chainTimer=.1;tick(w,.2);assert.equal(w.chain,0)});
test('rebel ending branch / persistent exploration',()=>{let w=fresh();w.won=true;w.roomSeen=true;w.player.x=3100;w.interact();assert(w.drain().some(e=>e.type==='ending'&&e.rebel));w.interact();assert(!w.drain().some(e=>e.type==='ending'))});
test('ten-minute randomized simulation stays finite',()=>{let w=fresh();let seed=12345;function rand(){seed=(seed*16807)%2147483647;return seed/2147483647}for(let i=0;i<72000;i++){if(i%60===0){let r=rand();if(r<.2)w.jump();else if(r<.4)w.dash();else if(r<.7)w.attack('light');else if(r<.85)w.attack('heavy',rand());else w.attack('electric')}w.update(1/120,{right:rand()>.3,left:rand()<.15});if(i%1000===0){w.drain();for(let k of ['x','y','hp','energy'])assert(Number.isFinite(w.player[k]))}}});
console.log(`\n${passed} scenario tests passed. All authored narrative branches exercised.`);
